//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDots.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DotWidth {
            get {
                return ((int)(this["DotWidth"]));
            }
            set {
                this["DotWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000")]
        public string DotColor {
            get {
                return ((string)(this["DotColor"]));
            }
            set {
                this["DotColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dot")]
        public string DotShape {
            get {
                return ((string)(this["DotShape"]));
            }
            set {
                this["DotShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LineWidth {
            get {
                return ((int)(this["LineWidth"]));
            }
            set {
                this["LineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFF")]
        public string LineColor {
            get {
                return ((string)(this["LineColor"]));
            }
            set {
                this["LineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastServer {
            get {
                return ((string)(this["LastServer"]));
            }
            set {
                this["LastServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastApi {
            get {
                return ((string)(this["LastApi"]));
            }
            set {
                this["LastApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAuthType {
            get {
                return ((string)(this["LastAuthType"]));
            }
            set {
                this["LastAuthType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUser {
            get {
                return ((string)(this["LastUser"]));
            }
            set {
                this["LastUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AllApis {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllApis"]));
            }
            set {
                this["AllApis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Seawater")]
        public string DotType {
            get {
                return ((string)(this["DotType"]));
            }
            set {
                this["DotType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF00")]
        public string MeasureColor {
            get {
                return ((string)(this["MeasureColor"]));
            }
            set {
                this["MeasureColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MeasureLineWidth {
            get {
                return ((int)(this["MeasureLineWidth"]));
            }
            set {
                this["MeasureLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MeasureFontSize {
            get {
                return ((int)(this["MeasureFontSize"]));
            }
            set {
                this["MeasureFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFileNavButtons {
            get {
                return ((bool)(this["ShowFileNavButtons"]));
            }
            set {
                this["ShowFileNavButtons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CircleWidth {
            get {
                return ((int)(this["CircleWidth"]));
            }
            set {
                this["CircleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction1 {
            get {
                return ((string)(this["AgeReadingKeyAction1"]));
            }
            set {
                this["AgeReadingKeyAction1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction2 {
            get {
                return ((string)(this["AgeReadingKeyAction2"]));
            }
            set {
                this["AgeReadingKeyAction2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction3 {
            get {
                return ((string)(this["AgeReadingKeyAction3"]));
            }
            set {
                this["AgeReadingKeyAction3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction4 {
            get {
                return ((string)(this["AgeReadingKeyAction4"]));
            }
            set {
                this["AgeReadingKeyAction4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction5 {
            get {
                return ((string)(this["AgeReadingKeyAction5"]));
            }
            set {
                this["AgeReadingKeyAction5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction6 {
            get {
                return ((string)(this["AgeReadingKeyAction6"]));
            }
            set {
                this["AgeReadingKeyAction6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction7 {
            get {
                return ((string)(this["AgeReadingKeyAction7"]));
            }
            set {
                this["AgeReadingKeyAction7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction8 {
            get {
                return ((string)(this["AgeReadingKeyAction8"]));
            }
            set {
                this["AgeReadingKeyAction8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selected Annotations")]
        public string GrowthAllMode {
            get {
                return ((string)(this["GrowthAllMode"]));
            }
            set {
                this["GrowthAllMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pixels")]
        public string GrowthAllScale {
            get {
                return ((string)(this["GrowthAllScale"]));
            }
            set {
                this["GrowthAllScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction9 {
            get {
                return ((string)(this["AgeReadingKeyAction9"]));
            }
            set {
                this["AgeReadingKeyAction9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction10 {
            get {
                return ((string)(this["AgeReadingKeyAction10"]));
            }
            set {
                this["AgeReadingKeyAction10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction11 {
            get {
                return ((string)(this["AgeReadingKeyAction11"]));
            }
            set {
                this["AgeReadingKeyAction11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction12 {
            get {
                return ((string)(this["AgeReadingKeyAction12"]));
            }
            set {
                this["AgeReadingKeyAction12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction13 {
            get {
                return ((string)(this["AgeReadingKeyAction13"]));
            }
            set {
                this["AgeReadingKeyAction13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction14 {
            get {
                return ((string)(this["AgeReadingKeyAction14"]));
            }
            set {
                this["AgeReadingKeyAction14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction15 {
            get {
                return ((string)(this["AgeReadingKeyAction15"]));
            }
            set {
                this["AgeReadingKeyAction15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction16 {
            get {
                return ((string)(this["AgeReadingKeyAction16"]));
            }
            set {
                this["AgeReadingKeyAction16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction17 {
            get {
                return ((string)(this["AgeReadingKeyAction17"]));
            }
            set {
                this["AgeReadingKeyAction17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction18 {
            get {
                return ((string)(this["AgeReadingKeyAction18"]));
            }
            set {
                this["AgeReadingKeyAction18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction19 {
            get {
                return ((string)(this["AgeReadingKeyAction19"]));
            }
            set {
                this["AgeReadingKeyAction19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction20 {
            get {
                return ((string)(this["AgeReadingKeyAction20"]));
            }
            set {
                this["AgeReadingKeyAction20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction21 {
            get {
                return ((string)(this["AgeReadingKeyAction21"]));
            }
            set {
                this["AgeReadingKeyAction21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction22 {
            get {
                return ((string)(this["AgeReadingKeyAction22"]));
            }
            set {
                this["AgeReadingKeyAction22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction23 {
            get {
                return ((string)(this["AgeReadingKeyAction23"]));
            }
            set {
                this["AgeReadingKeyAction23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction24 {
            get {
                return ((string)(this["AgeReadingKeyAction24"]));
            }
            set {
                this["AgeReadingKeyAction24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgeReadingKeyAction0 {
            get {
                return ((string)(this["AgeReadingKeyAction0"]));
            }
            set {
                this["AgeReadingKeyAction0"] = value;
            }
        }
    }
}
